### ISSUE TITLE
How to generate fir filters for 24k, low pass and high pass?

### ISSUE THREAD

**Issue by azraelkuan** [nii-yamagishilab/project-NN-Pytorch-scripts#1]
hi, i am runing a exp with 24khz audio, can u help me?
https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/blob/8c8318612e467c61c9d7d9315714e522bce3f2fe/project/hn-nsf/model.py#L594-L617

**Comment by TonyWangX** [comment]
Hi, 
(Although I haven't tried experiment on hn-nsf for 24kHz waveforms)

You can use the this website to calculate the filter coefficients
http://t-filter.engineerjs.com

1. Specify sampling freq to 24000 Hz
2. Change the upper bound of the stop/pass-band to 12000 Hz (rather than 8000)


For example, for lp_v, 

16kHz:
pass-band 0-5K, gain 1, ripple 5dB, 
stop-band 7-8k, gain 0, ripple -40dB

24kHz:
pass-band 0-5K, gain 1, ripple 5dB, 
stop-band 7-12k, gain 0, ripple -40dB

I uploaded one figure for the lp_v 24kHz configuration. The filter coefficients are shown on the right side.

Similarly, you may get the filter coefficients for other FIR filters.

![Screen Shot 2020-06-17 at 14 10 25](https://user-images.githubusercontent.com/16307017/84857614-6bec6100-b0a4-11ea-9994-a5ce6e4c997a.png)

**Comment by azraelkuan** [comment]
thanks!
