### ISSUE TITLE
VoicePrivacy2022 Baseline Tutorial xvectors size

### ISSUE THREAD

**Issue by simonspgn** [nii-yamagishilab/project-NN-Pytorch-scripts#47]
Hi, 

Thank you very much for the very insightful [tutorial](https://colab.research.google.com/drive/1_zRL_f9iyDvl_5Y2Rdakg0hYAl_5Rgyq?usp=sharing) of the 2022 edition of the VoicePrivacy baselines. 

Going through some of the steps for baseline B1.b, I found that you are using xvectors of size 256. When I extract the x-vectors myself (using Kaldi and the same pre-trained model as described in B1.b) I get vectors of size 512. The VoicePrivacy 2022 Evaluation Plan also mentions xvectors of size 512 in table 4 (page 11). Maybe I missed something but could you by any chance explain why the size difference? How could I reproduce the xvector extraction process to get the same 256-size xvector as you are using in the tutorial?

Thank you very much for your help!

**Comment by TonyWangX** [comment]
@simonspgn  Sorry for the confusion.  I forgot to mention it in the notebook.  I will add a note.

The 256-dimensional xvector is from sidekit (section 6.4.1
https://www.voiceprivacychallenge.org/vp2020/docs/VoicePrivacy_2022_Eval_Plan_v1.0.pdf) 
The reason was to move from KALDI to python-based tools, including the xvector part, but this has not been finished.


The sidekit xvector code is available in this branch:
https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022/tree/sidekit
I am not familiar with the sidekit, I just used what other colleagues provided. 
If you have questions on running sidekit, you can post issue there, Hubert and Pierre know more on the implementation than I do. 


Hope it helps!

**Comment by TonyWangX** [comment]
Hi @simonspgn 
are you able to get the sidekit xvector code running? 
If you need further help, let me know. I can ask the authors of sidekit xvector.

**Comment by simonspgn** [comment]
Hi @TonyWangX,

Apologies for not getting back to you earlier, yes I got everything to run smoothly with sidekit! 

Thank you very much again for the help and the super detailed work :)

**Comment by TonyWangX** [comment]
Thanks for the feedback!
