### ISSUE TITLE
LPCNet

### ISSUE THREAD

**Issue by zyxciel** [nii-yamagishilab/project-NN-Pytorch-scripts#50]
Thank you for opening up this fantastic repository, it has been a great help!  An error occurred when we try to synthesize some spoof speech using LPCNet. We find that __conver_pitch_ in line 613 of the blcok_lpcnet.py has a maximum value of 256, which conflicts with _nn.Embedding_ in line 570.  If the max of __conver_pitch_ is changed to 255, the program runs, but part of the speech amplitude is intermittent. Is there something wrong with our operation or is there any way to solve this problem? Thank you very much!

**Comment by TonyWangX** [comment]
Hi @zyxciel 
Sorry for my mistake, yes, it should be 

> torch.clamp((pitch_value - 33) // 2, 0, 255).to(torch.int64)

https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/blob/482c655987efc40b3ae4ce4321fa3a7131ea49c8/project/05-nn-vocoders/ilpcnet/block_lpcnet.py#L624

I think the change of the code should not hurt the quality because it will not change the output when (pitch_value - 33) // 2 is smaller than 256. 

Could you share with me the audio sample? I can have a check

**Comment by zyxciel** [comment]
Thank you very much! Here are two samples:
https://drive.google.com/drive/folders/1KtDybQKoFLdZcwHe6FvGtoM_LQIO7pXM?usp=sharing
But my colleague said that there was similar crash speech before changing the code, maybe there is something wrong with our feature extraction. Thank you again!

**Comment by TonyWangX** [comment]
Thanks for sending the samples. 

The abnormal sample is a typical example of when the autoregressive model fails during generation. The generated waveform amplitude was actually very large, but it was clipped to [-1, 1] when saving the raw data (i.e., tensor) into a PCM WAV format.  

The generated waveform amplitude  was large because the network fails to produce a "stable" excitation signal. Since we have forced the linear prediction filter to be stable, what can be wrong is the generated excitation signal.  This is a typical bad case when using an autoregressive model for inference. 

If you check this tensor step by step, I think you can see how abs(excit) becomes larger and larger https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/blob/482c655987efc40b3ae4ce4321fa3a7131ea49c8/project/05-nn-vocoders/ilpcnet/block_lpcnet.py#L812

To be honest, I don't have a deeper understanding of this issue. Neither do I know how to solve it.
In the past, I simply add more data and ran the training further, praying that it won't crash again.

If you have any idea on how to handle that, let me know : )

**Comment by zyxciel** [comment]
Thank you so much for your reply, it really helped us! I'm still new to vocoder and still have a lot to learn. 

Thank you again!

**Comment by TonyWangX** [comment]
@zyxciel 

On the code, I updated the line to
```sh
return torch.clamp((pitch_value - 33) // 2, 0, 
                   self.m_pitch_cat-1).to(torch.int64)
```
#51 
  
It worked on my side. Let me know whether it is OK for you. 


On the iLPCNet and WaveNet issue,  sure, if you have other questions, feel free to discuss.
(I've not worked on vocoders for some time, my views may be out-of-dated though).

**Comment by zyxciel** [comment]
No problem, it works fine for me, too. Thank you!
