### ISSUE TITLE
Can I use mgc extracted from WORLD?

### ISSUE THREAD

**Issue by OnceJune** [nii-yamagishilab/project-NN-Pytorch-scripts#8]
First of all, thanks for your amazing code.
When I read the paper https://arxiv.org/pdf/1810.11946.pdf, I found it used 60 dim MGC extracted by WOLRD.

> Acoustic features, including 60 dimensions of Melgeneralized cepstral coefficients (MGCs) [18] and 1 dimension of F0, were extracted from the 48 kHz waveforms at a frame shift of 5 ms using WORLD [19]. 

And in the config file project/01-nsf/hn-nsf/config.py, it becomes 80 dim mel spec.
Can I use the feature described in paper?
Thanks in advance.

**Comment by TonyWangX** [comment]
Hello, 

Sorry for the confusion. 

Both can be used, as long as they are acoustic features.  
And they have been compared in this extended study https://arxiv.org/pdf/1904.12088.pdf

I didn't put the MGC of WORLD because it is too troublesome: license, compiling of WORLD and SPTK, script for MGC ...
Mel-spectrogram is simple to implement and requires no additional dependency.
It is good for repository here.

As long as you become familiar with the (idiosyncratic) way this repository works, it is straightforward to replace Mel-spec with MGC -- just prepare the data and change config.py.

Note that WORLD and SPTK have Python wrappers, https://pypi.org/project/pyworld/, https://pypi.org/project/pysptk/.


You are welcome to contributing to this repository and adding support to other acoustic features.
(Apologize that I don't have time to do so ... )

**Comment by OnceJune** [comment]
@TonyWangX many thanks to your kind response.

**Comment by OnceJune** [comment]
@TonyWangX I tried to use WORLD feature and it works, thank you.
And when I try to do inference, I found the speed is a little bit slow.
By using CPU, I got:

> Start inference (generation):
> Generating 0,010662,0,42400,0, time: 3.906s
> Generating 1,020517,0,58800,0, time: 5.644s

While when it comes to GPU, the time cost is much faster:

> Start inference (generation):
> Generating 0,010662,0,42400,0, time: 0.410s
> Generating 1,020517,0,58800,0, time: 0.048s

![image](https://user-images.githubusercontent.com/5461945/116207314-5343e180-a772-11eb-9bdd-5355d78f172a.png)
Is this on GPU?

Thanks in advance.

**Comment by TonyWangX** [comment]
Hello, 
Yes, Table 3 is the result on GPU (P100). 

CPU is slow, see this notebook https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/blob/master/tutorials/s3_checkspeed_cpu.ipynb.

FYI:
Table 3 in the paper is obsolete now since our project has been moving on for a while.

---
Table 3 is the result using the **old** CUDA-implementation of NSF. 
There, the CUDA code used to have two working modes:
1. memory-save mode: "hard" release and allocation memory for long utterances 
2. normal mode: no memory release / allocation for short utterances.
Memory-save mode  was necessary for long utterances that require huge amount of GPU memory.
Memory-save mode was slow because of the "hard" GPU memory release / allocation.

In all:
memory-save mode -- GPU memory friendly, but slow
normal mode -- GPU memory hungry, but fast

---
For new CUDA-implementation (head of https://github.com/nii-yamagishilab/project-CURRENNT-scripts), 
there is only one fast memory mode:
1. fast memory-save mode: dynamic release and allocation memory
This is as fast as the old normal mode because we don't need multiple times of GPU memory allocation / release.
And it works for both long and short utterances, it is GPU memory friendly.

fast memory-normal mode -- GPU memory friendly, and fast

---
For Pytorch implementation, the Pytorch code automatically manages the GPU memory, 
and I didn't do further tuning on the generation speed. 

Pytorch -- I don't know the details, but to me it is GPU memory friendly, and fast

That's all

**Comment by OnceJune** [comment]
@TonyWangX Thanks. Now I finished all iterations and the abs result is really amazing.
